apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crossplane/crossplane
    targetRevision: v1.15.1
    chart: crossplane
    helm:
      releaseName: crossplane
      values: |
        args:
          - "--enable-external-secret-stores"
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
