apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/rustfs
    path: .
    targetRevision: "0.1.1"
    helm:
      values: |
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
