apiVersion: telemetry.yourorg.io/v1alpha1
kind: TelemetryPipeline
metadata:
  name: demo-pipeline
spec:
  tenant: demo
  namespace: observability
  signals:
    traces: true
    logs: true
    metrics: true
  storage:
    region: us-east-1
    tempoBucketName: demo-tempo-bucket
    lokiBucketName: demo-loki-bucket
    mimirBucketName: demo-mimir-bucket
  overrides:
    lokiValues:
      deploymentMode: SingleBinary
    tempoValues:
      deploymentMode: monolithic
  ingress:
    public: false
