apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tenant-2
spec: {}
status: {}
---

# Secret with MinIO chart values for credentials (placeholders)
apiVersion: v1
kind: Secret
metadata:
  name: minio-rustfs-credentials
  namespace: tenant-2
stringData:
  S3_ACCESS_KEY: "Jau7yiFYCl4TRQsBWL6j"
  S3_SECRET_KEY: "iDQmHEkGUpfjqy9uPhCV0FIZaJvW61cKxbrNTSL8"
---
apiVersion: example.crossplane.io/v1
kind: TelemetryPipeline
metadata:
  name: demo-pipeline-minio
  namespace: tenant-2
spec:
  tenant: demo
  namespace: tenant-2
  signals:
    traces: false
    logs: true
    metrics: false
  storage:
    region: us-east-1
    endpoint: rustfs.rustfs.svc.cluster.local:9000
    tempoBucketName: tempo-bucket
    lokiBucketName: loki-bucket
    mimirBucketName: mimir-bucket
    credentialSecretRef:
      name: minio-rustfs-credentials
      namespace: tenant-2
      access_key: S3_ACCESS_KEY
      secret_key: S3_SECRET_KEY
  overrides:
    grafanaValues:
      service:
        type: ClusterIP
    # Optional: override collector config if you need different pipelines
    # otelCollectorConfig: |
    #   receivers:
    #     otlp:
    #       protocols:
    #         grpc:
    #         http:
    #   exporters:
    #     logging: {}
    #   service:
    #     pipelines:
    #       traces:
    #         receivers: [otlp]
    #         exporters: [logging]
